version: "3.8"
services:
  docker_postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: safePassword123!
      POSTGRES_USER: shopifyAdmin
      POSTGRES_DB: logistics
      PGDATA: pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/qj:z
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:z
      # Note that the file extensions need to be sql files, not ddl files.
    command: -p 5433
    ports:
      - "5433:5432"
    networks:
      - default
  logistics:
    build: .
    environment:
      NODE_ENV: development
    depends_on:
      - docker_postgres
    ports:
      - "3001:3001"
    networks:
      - default
  html:
    build: ./html
    ports:
      - "80:80"
    networks:
      - default
