version: "3.8"
services:
  postgres_alone:
    image: postgres
    environment:
      POSTGRES_PASSWORD: safePassword123!
      POSTGRES_USER: shopifyAdmin
      POSTGRES_DB: logistics
      PGDATA: pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/qj:z
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:z
    ports:
      - "5434:5432"
    networks:
      - default
