version: "3.8"
services:
    postgres_alone:
        image: postgres
        environment:
            POSTGRES_PASSWORD: Yatathakar123!
            POSTGRES_USER: qj
            POSTGRES_DB: quranJourney
            PGDATA: pgdata
        volumes:
            - ./pgdata:/var/lib/postgresql/qj:z
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:z
            - ./views.sql:/docker-entrypoint-initdb.d/views.sql:z
        ports:
            - "5434:5432"
        networks:
            - default